inputs:
  - name: cna-iaas-smoke-test

jobs:
- name: iaas-smoke-test
  public: true
  serial: true
  plan:
  - aggregate:
    - get: iaas-smoke-test-release
    - get: cna-iaas-smoke-test
  - aggregate:
    - task: run_host1
      file: cna-iaas-smoke-test/ci/run_host.yml
      params:
        host_name: {{host1_name}}
        host_user: {{host1_user}}
        host_password: {{host1_password}}
        host_path: {{host1_path}}
        host_platform: {{host1_platform}}
    - task: run_host2
      file: cna-iaas-smoke-test/ci/run_host.yml
      params:
        host_name: {{host2_name}}
        host_user: {{host2_user}}
        host_password: {{host2_password}}
        host_path: {{host2_path}}
        host_platform: {{host2_platform}}
  - aggregate:
    - task: run_test1
      file: cna-iaas-smoke-test/ci/run_test.yml
      params:
        host_name: {{host1_name}}
        host_user: {{host1_user}}
        host_password: {{host1_password}}
        host_path: {{host1_path}}
        host_platform: {{host1_platform}}
    - task: run_test2
      file: cna-iaas-smoke-test/ci/run_test.yml
      params:
        host_name: {{host2_name}}
        host_user: {{host2_user}}
        host_password: {{host2_password}}
        host_path: {{host2_path}}
        host_platform: {{host2_platform}}
resources:
- name: iaas-smoke-test-release
  type: github-release
  source:
    user: ECSTeam
    repository: IaaSSmokeTest
# - name: cna-iaas-smoke-test
#   type: git
#   source:
#     uri: https://github.com/wrast/cna-iaas-smoke-test.git
