
# host 1 - ECS linux jump box
host1_name: 172.29.0.18
host1_user: user1
host1_password: Ecsl@b99
host1_path: .
host1_prompt: "$ "
host1_platform: linux

# host 2
host2_name: ecsdenlabvc01.lab.ecsteam.local
host2_user: root
host2_password: Ecsl@b99
host2_path: .
host2_prompt: "# "
host2_platform: linux
