
# host 1 - ubuntu host
host1_name: 172.28.90.232
host1_user: wrast
host1_password: welcome1
host1_path: .
host1_prompt: "$ "
host1_platform: linux

# host 2
host2_name: 172.28.90.233
host2_user: wrast
host2_password: welcome1
host2_path: .
host2_prompt: "$ "
host2_platform: linux
