jobs:
- name: job-github-release
  public: true
  serial: true
  plan:
  - get: iaas-smoke-test-release
  - get: cna-iaas-smoke-test
  - task: create
    file: cna-iaas-smoke-test/ci/create.yml
  - task: scp
    file: cna-iaas-smoke-test/ci/scp.yml
resources:
- name: iaas-smoke-test-release
  type: github-release
  source:
    user: ECSTeam
    repository: IaaSSmokeTest
- name: cna-iaas-smoke-test
  type: git
  source:
    uri: https://github.com/wrast/cna-iaas-smoke-test.git
